---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci

inputs:
  - name: buildpack-master
  - name: buildpacks-ci
  - name: pivnet-dotnet-core-metadata

outputs:
  - name: pivnet-dotnet-core-metadata-out

run:
  path: buildpacks-ci/tasks/write-pivnet-metadata/run.rb
